---
- name: Install Docker
  dnf:
    name:
      - docker
      - docker-compose
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /home/ansible/docker-compose.yml
    mode: '0644'

- name: Copy Prometheus configuration
  copy:
    src: prometheus.yml
    dest: /home/ansible/prometheus.yml
    mode: '0644'

- name: Run docker-compose
  command: docker-compose -f /home/ansible/docker-compose.yml up -d